# -*- coding: utf-8 -*-
"""fire-detection-master.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xJBVmaUTyAoi-0GI3ksuqo0ViTnyCaNu
"""

import kagglehub
path = kagglehub.dataset_download("kutaykutlu/forest-fire")

import os
import cv2
import kagglehub
import shutil
import random

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split

from tensorflow.keras.preprocessing.image import (
    ImageDataGenerator,
    img_to_array
)

from tensorflow.keras.applications import EfficientNetB0
from tensorflow.keras.applications.efficientnet import preprocess_input

from tensorflow.keras.models import (
    Model,
    load_model
)

from tensorflow.keras.layers import (
    Dense,
    Dropout,
    GlobalAveragePooling2D
)

from tensorflow.keras.optimizers import Adam

from tensorflow.keras.callbacks import (
    EarlyStopping,
    ModelCheckpoint
)

from sklearn.metrics import (
    confusion_matrix,
    classification_report
)

# ============================================================
# DOWNLOAD DATASET
# ============================================================

print("\nDownloading Dataset...")

path = kagglehub.dataset_download(
    "kutaykutlu/forest-fire"
)

print("\nDataset Path:")
print(path)

# ============================================================
# DATASET PREPARATION
# ============================================================

# Create folders

base_dir = "forest_fire_dataset"

train_fire = os.path.join(base_dir, "train/fire")
train_non_fire = os.path.join(base_dir, "train/non_fire")

test_fire = os.path.join(base_dir, "test/fire")
test_non_fire = os.path.join(base_dir, "test/non_fire")

os.makedirs(train_fire, exist_ok=True)
os.makedirs(train_non_fire, exist_ok=True)

os.makedirs(test_fire, exist_ok=True)
os.makedirs(test_non_fire, exist_ok=True)

# ============================================================
# FIND IMAGE FILES
# ============================================================

all_images = []

for root, dirs, files in os.walk(path):

    for file in files:

        if file.endswith( (".jpg", ".png", ".jpeg") ):

            all_images.append(
                os.path.join(root, file)
            )

print(f"\nTotal Images Found: {len(all_images)}")

# ============================================================
# CLASSIFY IMAGES
# ============================================================

fire_images = []
non_fire_images = []

for image_path in all_images:
    # Check for directory patterns that indicate 'fire'
    # The dataset structure typically has 'Fire_Dataset/Fire' and also 'train_fire'
    if '/Fire_Dataset/Fire/' in image_path or '/train_fire/' in image_path:
        fire_images.append(image_path)
    # Check for directory patterns that indicate 'non_fire'
    # The dataset structure typically has 'Fire_Dataset/Non_Fire' and also 'train-smoke'
    elif '/Fire_Dataset/Non_Fire/' in image_path or '/train-smoke/' in image_path:
        non_fire_images.append(image_path)
    # Images in 'test_big' might be mixed or require further classification,
    # but for now, we prioritize getting images into the train/test sets for the existing classes.
    # If an image path doesn't contain these clear indicators, it will be skipped.

print(f"\nFire Images: {len(fire_images)}")
print(f"Non Fire Images: {len(non_fire_images)}")

# ============================================================
# TRAIN TEST SPLIT
# ============================================================

train_fire_split, test_fire_split = train_test_split(
    fire_images,
    test_size=0.2,
    random_state=42
)

train_non_fire_split, test_non_fire_split = train_test_split(
    non_fire_images,
    test_size=0.2,
    random_state=42
)

# ============================================================
# COPY FILES
# ============================================================

def copy_images(image_list, destination):

    for image_path in image_list:

        try:

            shutil.copy(
                image_path,
                destination
            )

        except:
            continue

copy_images(train_fire_split, train_fire)
copy_images(test_fire_split, test_fire)

copy_images(train_non_fire_split, train_non_fire)
copy_images(test_non_fire_split, test_non_fire)

print("\nDataset Organized Successfully")

# ============================================================
# CLASS LABELS
# ============================================================

classes = ['fire', 'non_fire']

NUM_CLASSES = len(classes)

# ============================================================
# IMAGE SETTINGS
# ============================================================

IMG_SIZE = 224
BATCH_SIZE = 32

# ============================================================
# VISUALIZE SAMPLE IMAGES
# ============================================================

def show_sample_images():

    plt.figure(figsize=(10,5))

    for i, class_name in enumerate(classes):

        folder = os.path.join(
            base_dir,
            "train",
            class_name
        )

        image_name = random.choice(
            os.listdir(folder)
        )

        image_path = os.path.join(
            folder,
            image_name
        )

        image = cv2.imread(image_path)

        image = cv2.cvtColor(
            image,
            cv2.COLOR_BGR2RGB
        )

        plt.subplot(1,2,i+1)

        plt.imshow(image)

        plt.title(class_name)

        plt.axis("off")

    plt.show()

show_sample_images()

# ============================================================
# DATA AUGMENTATION
# ============================================================

train_datagen = ImageDataGenerator(
    preprocessing_function=preprocess_input,
    rotation_range=20,
    zoom_range=0.2,
    horizontal_flip=True,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.2
)

test_datagen = ImageDataGenerator(
    preprocessing_function=preprocess_input
)

# ============================================================
# LOAD DATASET
# ============================================================

train_generator = train_datagen.flow_from_directory(
    os.path.join(base_dir, "train"),
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode='categorical'
)

test_generator = test_datagen.flow_from_directory(
    os.path.join(base_dir, "test"),
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    shuffle=False
)

# ============================================================
# BUILD MODEL
# ============================================================

base_model = EfficientNetB0(
    weights='imagenet',
    include_top=False,
    input_shape=(IMG_SIZE, IMG_SIZE, 3)
)

# Freeze pretrained layers
for layer in base_model.layers:

    layer.trainable = False

x = base_model.output

x = GlobalAveragePooling2D()(x)

x = Dense(
    256,
    activation='relu'
)(x)

x = Dropout(0.5)(x)

predictions = Dense(
    NUM_CLASSES,
    activation='softmax'
)(x)

model = Model(
    inputs=base_model.input,
    outputs=predictions
)

# ============================================================
# COMPILE MODEL
# ============================================================

model.compile(
    optimizer=Adam(learning_rate=0.0001),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

# ============================================================
# CALLBACKS
# ============================================================

checkpoint = ModelCheckpoint(
    "best_forest_fire_model.h5",
    monitor='val_accuracy',
    save_best_only=True,
    verbose=1
)

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=5,
    restore_best_weights=True
)

# ============================================================
# TRAIN MODEL
# ============================================================

history = model.fit(
    train_generator,
    validation_data=test_generator,
    epochs=5,
    steps_per_epoch=100,
    callbacks=[checkpoint, early_stop]
)

# ============================================================
# SAVE MODEL
# ============================================================

model.save(
    "final_forest_fire_model.h5"
)

print("\n✅ Model Saved Successfully")

# ============================================================
# ACCURACY GRAPH
# ============================================================

plt.figure(figsize=(10,5))

plt.plot(
    history.history['accuracy'],
    label='Training Accuracy'
)

plt.plot(
    history.history['val_accuracy'],
    label='Validation Accuracy'
)

plt.title("Model Accuracy")

plt.xlabel("Epoch")

plt.ylabel("Accuracy")

plt.legend()

plt.show()

# ============================================================
# LOSS GRAPH
# ============================================================

plt.figure(figsize=(10,5))

plt.plot(
    history.history['loss'],
    label='Training Loss'
)

plt.plot(
    history.history['val_loss'],
    label='Validation Loss'
)

plt.title("Model Loss")

plt.xlabel("Epoch")

plt.ylabel("Loss")

plt.legend()

plt.show()

# ============================================================
# MODEL EVALUATION
# ============================================================

loss, accuracy = model.evaluate(
    test_generator
)

print(
    f"\n✅ Test Accuracy: {accuracy*100:.2f}%"
)

# ============================================================
# PREDICTIONS
# ============================================================

predictions = model.predict(
    test_generator
)

y_pred = np.argmax(
    predictions,
    axis=1
)

# ============================================================
# CONFUSION MATRIX
# ============================================================

cm = confusion_matrix(
    test_generator.classes,
    y_pred
)

plt.figure(figsize=(6,6))

sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=classes,
    yticklabels=classes
)

plt.xlabel("Predicted")

plt.ylabel("Actual")

plt.title("Confusion Matrix")

plt.show()

# ============================================================
# CLASSIFICATION REPORT
# ============================================================

print("\nClassification Report:\n")

print(
    classification_report(
        test_generator.classes,
        y_pred,
        target_names=classes
    )
)

# ============================================================
# REAL-TIME WEBCAM DETECTION
# ============================================================

model = load_model(
    "final_forest_fire_model.h5"
)

cap = cv2.VideoCapture(0)

print("\n🔥 Starting Forest Fire Detection")
print("Press Q to Exit")

while True:

    ret, frame = cap.read()

    if not ret:
        break

    resized = cv2.resize(
        frame,
        (IMG_SIZE, IMG_SIZE)
    )

    processed = img_to_array(
        resized
    )

    processed = np.expand_dims(
        processed,
        axis=0
    )

    processed = preprocess_input(
        processed
    )

    prediction = model.predict(
        processed
    )

    class_index = np.argmax(
        prediction
    )

    confidence = np.max(
        prediction
    )

    label = classes[class_index]

    # Fire = Red
    # Non Fire = Green

    if label == "fire":

        color = (0,0,255)

    else:

        color = (0,255,0)

    cv2.putText(
        frame,
        f"{label} : {confidence*100:.2f}%",
        (20,40),
        cv2.FONT_HERSHEY_SIMPLEX,
        1,
        color,
        2
    )

    cv2.imshow(
        "Forest Fire Detection System",
        frame
    )

    if cv2.waitKey(1) & 0xFF == ord('q'):

        break

cap.release()

cv2.destroyAllWindows()

# ============================================================
# END OF PROJECT
# ============================================================

#
# IMPORTANT IMPROVEMENTS YOU SHOULD ADD:
#
# 1. Streamlit Dashboard
# 2. Email Alert System
# 3. Telegram Alert
# 4. YOLOv8 Fire Localization
# 5. Smoke Detection
# 6. Cloud Deployment
#
# ============================================================

"""### Real-Time Detection using a Video File

Since direct webcam access is not available in Google Colab, you can use a video file for real-time detection. Replace `'path/to/your/video.mp4'` with the actual path to your video file. You can upload a video file to your Colab environment or provide a path to a file already present in your mounted Google Drive or Kaggle input data.
"""

# ============================================================
# REAL-TIME VIDEO FILE DETECTION
# ============================================================

# Import the Colab-compatible imshow
from google.colab.patches import cv2_imshow

# Load the trained model
model = load_model(
    "final_forest_fire_model.h5"
)

# Using the provided GIF file as the video source
cap = cv2.VideoCapture('/content/video_2.gif')

if not cap.isOpened():
    print("Error: Could not open video file. Please ensure the path is correct and the file is accessible.")
else:
    print("\n🔥 Starting Forest Fire Detection on video file")
    print("Press Q to Exit")

    while True:

        ret, frame = cap.read()

        if not ret:
            print("End of video stream or error reading frame.")
            break

        resized = cv2.resize(
            frame,
            (IMG_SIZE, IMG_SIZE)
        )

        processed = img_to_array(
            resized
        )

        processed = np.expand_dims(
            processed,
            axis=0
        )

        processed = preprocess_input(
            processed
        )

        prediction = model.predict(
            processed
        )

        class_index = np.argmax(
            prediction
        )

        confidence = np.max(
            prediction
        )

        label = classes[class_index]

        # Fire = Red
        # Non Fire = Green

        if label == "fire":

            color = (0,0,255)

        else:

            color = (0,255,0)

        cv2.putText(
            frame,
            f"{label} : {confidence*100:.2f}%",
            (20,40),
            cv2.FONT_HERSHEY_SIMPLEX,
            1,
            color,
            2
        )

        # Use the Colab-compatible imshow
        cv2_imshow(
            frame
        )

        if cv2.waitKey(1) & 0xFF == ord('q'):

            break

    cap.release()

    cv2.destroyAllWindows()

# ============================================================
# END OF VIDEO FILE DETECTION
# ============================================================